API Changes
natmlx/NatML-JS pull request #3
Opened 2022-01-16 02:16 UTC by ethanresnick

@olokobayusuf This implements all the API changes discussed in #2, and lays the ground work for making the package isomorphic (though I'm going to push more of that work up in a separate PR; this is already pretty big as is).

As part of this PR, I set up prettier to run on every commit, so there's a lot of noise in this diff from the initial format. But, if you review the PR commit by commit (and just skip over the giant "format" commit), it should be easy enough to follow.

2022-01-16 22:47 UTC, olokobayusuf requested changes
Hey @ethanresnick overall everything looks good. I have some comments, and at least one requested change. Minor note on linting: can we configure `prettier` to not add semicolons on import statements? This is a convention that I use in JS/TS:
```typescript
import { BlahBlah } from "blah-blah" // No semicolon
```

2022-01-16 22:47 UTC, olokobayusuf commented on src/types/MLImageType.ts
> +  public readonly interleaved: boolean;
This should remain `private`. Clients don't need to know this; it's an internal detail.

2022-01-17 00:12 UTC, ethanresnick commented on src/utils/fpHelpers.ts
> +  };
Hehe. I’m sure you get the idea though, which is to add something that feels almost as nice as built-in syntactic pattern matching, using a helper function

2022-01-17 00:38 UTC, ethanresnick commented on src/features/MLImageFeature.ts
> +   * in declaration export files, but should be treated as private.
That comment actually doesn’t apply to the code in its current state in this PR, but it will apply when i finish making the code isomorphic.

Since the strategy is going to be to export a function that takes the dependencies as an argument and then returns the class (since classes are runtime values in JS), TS needs a way to type the return type of that function (which should be the class type). If a returned class has private members, though, TS doesn’t support serializing those in .d.ts files (which strikes me as something that should be very solvable, but for some reason hasn’t been).

I just dug up [the issue](https://github.com/microsoft/TypeScript/issues/30355), and it looks like there are some workarounds that are arguably better than using an underscore-prefixed public property, so i’ll give those a go.

2022-01-17 00:42 UTC, ethanresnick commented on src/features/MLImageFeature.ts
>    ) {
Agreed, it would be nice

2022-01-17 00:44 UTC, ethanresnick commented on src/hub/MLHubModel.ts
> +    const results = prediction.results!; // TODO: non-null assertion safe?
Will update the types accordingly

2022-01-17 00:44 UTC, ethanresnick commented on src/features/MLImageFeature.ts
> +    return [data, type, attributes] as const;
Yeah, the TS type system is awesome

2022-01-17 00:53 UTC, ethanresnick commented on src/features/MLImageFeature.ts
> +   * in declaration export files, but should be treated as private.
For now, i’ll just go back to marking the properties as private, and then apply the workaround when i make the code isomorphic

2022-01-17 00:55 UTC, ethanresnick commented
@olokobayusuf Thanks for the thorough review. Will push updates soon. For the prettier config, there isn’t an option to have it put semicolons after every statement except import declarations; the only options are to include semicolons after every statement, or to never put semicolons unless they’re absolutely necessary (because of some edge cases where they can’t be inferred).

2022-01-17 08:19 UTC, ethanresnick commented
@olokobayusuf Ok, I pushed fixes to all your comments. The last commit might be of interest, since it leverages some type-level programming to better capture the runtime behavior, in a way that C# can't.

With your comments addressed, I'm gonna move on to the isomorphic stuff, and push those changes to this branch too.

2022-01-17 15:37 UTC, olokobayusuf commented on src/features/MLImageFeature.ts
> +   * in declaration export files, but should be treated as private.
Okay this is good to know. Thanks for the explanation!

2022-01-17 15:44 UTC, olokobayusuf requested changes

2022-01-17 15:44 UTC, olokobayusuf commented on src/hub/NatMLHub.ts
> +> {
Any reason for `WaitUntilComplete extends boolean`?

2022-01-17 15:44 UTC, olokobayusuf commented on src/hub/NatMLHubTypes.ts
> +export type Prediction = IncompletePrediction | CompletedPrediction;
I understand the intent with creating types that are more expressive of the underlying states that are possible within a `Prediction`, but isn't the benefit of such types marginal especially compared to the added cognitive load of the added types? My (strong) preference is to retain simple types, without introducing these more specific sub-types.

2022-01-17 15:45 UTC, olokobayusuf commented
>  For the prettier config, there isn’t an option to have it put semicolons after every statement except import declarations; the only options are to include semicolons after every statement, or to never put semicolons unless they’re absolutely necessary (because of some edge cases where they can’t be inferred).

That's fine, we can keep it as is.

> Ok, I pushed fixes to all your comments. The last commit might be of interest, since it leverages some type-level programming to better capture the runtime behavior, in a way that C# can't.

I appreciate the use of more *correct* types, expressing the state of the `Prediction` object, but I think that the added cognitive load isn't worth whatever marginal benefit we get. My preference is to keep these types as simple/dumb as possible.

2022-01-17 21:14 UTC, ethanresnick commented on src/hub/NatMLHub.ts
> +> {
`WaitUntilComplete extends boolean` means that the generic param can only be instantiated with a type that's a subtype of boolean (analogous to `T : bool` in C#). However, in TS, `true` and `false` are [literal types](https://www.typescriptlang.org/docs/handbook/literal-types.html), so this is saying that the type parameter can be instantiated with 3 possible types: `true`, `false`, or `boolean`

2022-01-17 22:17 UTC, ethanresnick commented
> I appreciate the use of more correct types, expressing the state of the Prediction object, but I think that the added cognitive load isn't worth whatever marginal benefit we get. My preference is to keep these types as simple/dumb as possible.

So, one thing I'm realizing from your mention of "cognitive load" is that I could have written the types more simply, while still preserving the added precision, with something like this:

```ts
export type Prediction = IncompletePrediction | CompletePrediction;

export type IncompletePrediction = {
  id: string;
  status: Exclude<PredictionStatus, PredictionStatus.Completed>;
  results: null;
  error: null;
};

// If prediction is completed, it must have an error or results, and not both.
export type CompletePrediction = ErroredPrediction | SuccessfulPrediction;

export type ErroredPrediction = {
  id: string;
  status: PredictionStatus.Completed;
  results: null;
  error: string;
};

export type SuccessfulPrediction = {
  id: string;
  status: PredictionStatus.Completed;
  // results is an array of MLHubFeatures, except the data is a
  // URL string to remote data or base64-encoded data in a data url.
  results: (Omit<MLHubFeature, "data"> & { data: string })[];
  error: null;
};
```

My preference would be to update the types to be like that, but I'll switch back to just having one `Prediction` interface if you want. Let me give you my reasoning first, though, for breaking the types out...

How I think about it is: 

There are a bunch of facts about how NatML works — for example, that a prediction can't have both an error and results (which is possible in many systems that support a notion of "partial success"), and that there are expected states (namely, the pending ones) where a prediction will have _neither_ an error or results. 

These sorts of "system facts" won't always be obvious, especially to new programmers coming to the codebase. But all the programmers will still have to know these details in order to write correct code. Therefore, the information has to be documented somewhere that people will actually read and update. More than that, though, the programmer has to (correctly) remember each rule in every place where it might apply, and make sure the code accounts for it. 

To me, that process of remembering all the details about the system in every case they might apply is the real cognitive load. The value of documenting those details in the types is that you're then outsourcing that cognitive load to the compiler. You don't have to answer questions like: "Am I sure there's no case here where this will be null?", because the compiler's checked it for you (and is more likely to get it right).

I agree with you, of course, that it takes some amount of work to read/interpret the types. But I think that values of a given type tend to be used (at which point accompanying compiler errors are a helpful guide) much more often than the type definition itself is read, so this becomes a good tradeoff. And, when the type definition is read, a more precise type will provide more useful documentation.

Also, a lot of the of the cognitive load of decoding the types is from the complexity of TS's syntax and advanced features; that cost goes down over time, as programmers get more familiar with Typescript, and that skill of reading TS transfers across projects. That isn't true of the system facts, which are different for each project.

The last thing is that, when the system changes — e.g., imagine there's some new prediction status, or anew "partial success" case where both an error and a result could be present — refactoring the code to account for the new system rules is _much, much_ safer/easier/more reliable when the old rules were encoded more precisely.

Granted, I do think type-level modeling can be taken too far, where the types get so complicated that the skill and time involved in decoding them gets so high that it isn't worth it. (A lot of the types in the react ecosystem fall into that bucket imo.) But, at least with the rewritten version above, I'd say these more precise Prediction types are pretty far from that line, at least where I'm inclined to draw it.

2022-01-23 22:48 UTC, olokobayusuf commented
> So, one thing I'm realizing from your mention of "cognitive load" is that I could have written the types more simply, while still preserving the added precision, with something like this:

This is a good compromise; I'm fine with it.

> To me, that process of remembering all the details about the system in every case they might apply is the real cognitive load. The value of documenting those details in the types is that you're then outsourcing that cognitive load to the compiler. You don't have to answer questions like: "Am I sure there's no case here where this will be null?", because the compiler's checked it for you (and is more likely to get it right).

This is a fair point. Normally, I'd counter this by stating that these conditions are stated in the [API docs](https://docs.natml.ai/graph), but I know from experience that nobody reads the docs. So I agree, this is a practical solution to reducing cognitive load while keeping devs aware of these quirks.

> Also, a lot of the of the cognitive load of decoding the types is from the complexity of TS's syntax and advanced features; that cost goes down over time, as programmers get more familiar with Typescript, and that skill of reading TS transfers across projects. That isn't true of the system facts, which are different for each project.

TS's type system (to me) can get quite complicated; it's meta-programming capabilities are up there (with say C++). Almost no other language I know of has similar meta-programming capabilities, so I'd push back a bit on a developer's ability to transfer this to other languages. Besides this I agree.

> The last thing is that, when the system changes — e.g., imagine there's some new prediction status, or anew "partial success" case where both an error and a result could be present — refactoring the code to account for the new system rules is much, much safer/easier/more reliable when the old rules were encoded more precisely.

This is an incredibly compelling point--one that I haven't though about. Thanks for taking the time to bring it up!

2022-01-23 23:15 UTC, ethanresnick commented
> This is a good compromise; I'm fine with it.
👍 

>  Almost no other language I know of has similar meta-programming capabilities, so I'd push back a bit on a developer's ability to transfer this to other languages.

Fair enough; I was mostly talking about transferring the knowledge to other TS projects, rather than projects in other languages. That said, there actually are many languages that have quite advanced "type-level programming" capabilities. Granted, a lot of these are very rare in practice (e.g., Idris, Coq, Haskell), but I think some are approaching mainstream-ish adoption — notably Scala and Rust. My guess, though, is that we'll start to see more and more of these type system features trickle into mainstream languages, in precisely the same way that functional programming concepts have.

2022-02-01 09:08 UTC, merged